<!DOCTYPE html><!-- these lines were generated by Mithril Emmet addon -->
<html lang="en"><!-- these lines were generated by Mithril Emmet addon -->

<head>
    <meta charset="UTF-8"><!-- these lines were generated by Mithril Emmet addon -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge"><!-- these lines were generated by Mithril Emmet addon -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"><!-- these lines were generated by Mithril Emmet addon -->
    <title><?php echo $pageTitle;?></title><!-- these lines were generated by Mithril Emmet addon -->
</head><!-- these lines were generated by Mithril Emmet addon -->