<!DOCTYPE html><!-- these lines were generated by Mithril Emmet addon -->
<html lang="en">
<!-- these lines were generated by Mithril Emmet addon -->

<head>
    <meta charset="UTF-8"><!-- these lines were generated by Mithril Emmet addon -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge"><!-- these lines were generated by Mithril Emmet addon -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- these lines were generated by Mithril Emmet addon -->
    <title><?php echo $pageTitle;?></title><!-- these lines were generated by Mithril Emmet addon -->
    <style>
        body {
            width: 80vw;
            margin: 0 auto;
        }

        .people-table th,
        .people-table td,
        .ownership-container th,
        .ownership-container td {
            background-color: #dddddd;
        }

        .people-table,
        {
        width: 80 vw;
        }

        .ownership-container {
            width: 600px;
            margin: 2em auto;
        }

        .ownership-container table {
            width: 500px;
            border: 1px black solid;
            margin: auto auto;
        }

        .ownership-container td {
            width: 50%;
        }

        .feedback-red {
            background-color: #ff999c;
            width: 100%;
            border-radius: 0.5em;
            margin: 0.5em auto;
        }

        .feedback-yellow {
            background-color: #efd73c;
            width: 100%;
            border-radius: 0.5em;
            margin: 0.5em auto;
        }

        .feedback-green {
            background-color: #b7ffb4;
            width: 100%;
            border-radius: 0.5em;
            margin: 0.5em auto;
        }

        .feedback-text-line {
            margin: 0em auto;
            padding: 0.5em;
            width: fit-content;
        }

        /* for .uneditable, I referenced this: https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events */
        .uneditable {
            pointer-events: none;
            background-color: #dedede;
        }

        .uneditable:hover {
            cursor: not-allowed;
        }

        .text-green {
            color: green;
        }

        .text-red {
            color: red;
        }
    </style>
</head><!-- these lines were generated by Mithril Emmet addon -->