<!DOCTYPE html><!-- these lines were generated by Mithril Emmet addon -->
<html lang="en"><!-- these lines were generated by Mithril Emmet addon -->

<head>
    <meta charset="UTF-8"><!-- these lines were generated by Mithril Emmet addon -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge"><!-- these lines were generated by Mithril Emmet addon -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"><!-- these lines were generated by Mithril Emmet addon -->
    <title><?php echo $pageTitle;?></title><!-- these lines were generated by Mithril Emmet addon -->
    <style>
        .people-table th, .people-table td, .ownership-container th, .ownership-container td {
            background-color: #dddddd;
        }
        .people-table, {
            width: 80 vw;
        }
        .ownership-container {
            width: 600px;
            margin: 2em auto;
        }
        .ownership-container table {
            width: 500px;
            border: 1px black solid;
            margin: auto auto;
        }
        .ownership-container td {
            width: 50%;
        }
    </style>
</head><!-- these lines were generated by Mithril Emmet addon -->