<!DOCTYPE html><!-- these html element lines were generated by a vs code extension named Mithril Emmet -->
<html lang="en">
<!-- these html element lines were generated by a vs code extension named Mithril Emmet -->

<head>
    <meta charset="UTF-8"><!-- these html element lines were generated by a vs code extension named Mithril Emmet -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- these html element lines were generated by a vs code extension named Mithril Emmet -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- these html element lines were generated by a vs code extension named Mithril Emmet -->
    <title><?php echo $pageTitle;?></title>
    <!-- these html element lines were generated by a vs code extension named Mithril Emmet -->

    <link rel="stylesheet" type="text/css" href="../reuse/styles.css">
    <!-- the link tag referenced: https://www.freecodecamp.org/news/how-to-link-css-to-html/-->

</head><!-- these html element lines were generated by a vs code extension named Mithril Emmet -->